/* SPDX-License-Identifier: GPL-2.0 */
#ifndef CHARGER_PARTITION_H
#define CHARGER_PARTITION_H

#define CHARGER_WORK_DELAY_MS 5000
#define CHARGER_PARTITION_RETRY_TIMES 20
#define PARTITION_NAME "charger"
#define CHARGER_PARTITION_MAXSIZE 0x10000
#define CHARGER_PARTITION_RWSIZE 0x1000
#define CHARGER_PARTITION_OFFSET 0
#define UFSHCD "ufshcd"
#define PART_SECTOR_SIZE 0x200
#define PART_BLOCK_SIZE 0x1000
#define CHARGER_PARTITION_MAX_BLOCK_TRANSFERS 128

enum charger_partition_attr_list {
	MCA_PROP_CHARGER_PARTITION_MISHOW,
	MCA_PROP_CHARGER_PARTITION_POWEROFFMODE,
	MCA_PROP_CHARGER_PARTITION_PROP_EU_MODE,
};

#endif
