obj-$(CONFIG_XM_POWER_SUPPLY) += mca_strategy_class.o
obj-$(CONFIG_XM_POWER_SUPPLY) += strategy_fg/
obj-$(CONFIG_XM_POWER_SUPPLY) += strategy_buckchg/
obj-$(CONFIG_XM_POWER_SUPPLY) += strategy_jeita/
obj-$(CONFIG_XM_POWER_SUPPLY) += strategy_quickchg/
obj-$(CONFIG_XM_POWER_SUPPLY) += strategy_thermal/
obj-$(CONFIG_XM_POWER_SUPPLY) += strategy_pd_auth/
obj-$(CONFIG_XM_POWER_SUPPLY) += strategy_soc_limit/
