obj-$(CONFIG_XM_POWER_SUPPLY) += mca_platform_cp_class.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_platform_fg_ic_ops.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_platform_buckchg_class.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_platform_bc12_class.o

# Load-switch and wireless classes follow after wired charging is validated.
