# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY) += mca_wireless_class_compat.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_basic_wireless.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_quick_wireless_baa.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_wireless_revchg_safe.o
