#ifndef _MCA_COMMON_MCA_EVENT_H_
#define _MCA_COMMON_MCA_EVENT_H_

#include <linux/notifier.h>

#define MCA_EVENT_NOTIFY_SIZE 128
#define MCA_EVENT_WR_BUF_SIZE 128

enum mca_event_type {
	MCA_EVENT_TYPE_BEGIN = 0,
	MCA_EVENT_TYPE_CHARGER_CONNECT = MCA_EVENT_TYPE_BEGIN,
	MCA_EVENT_TYPE_CHARGE_TYPE,
	MCA_EVENT_TYPE_BATTERY_INFO,
	MCA_EVENT_TYPE_CP_INFO,
	MCA_EVENT_TYPE_HW_INFO,
	MCA_EVENT_CHARGE_STATUS,
	MCA_EVENT_TYPE_THERMAL_TEMP,
	MCA_EVENT_TYPE_PANEL,
	MCA_EVENT_TYPE_TYPEC_PORT_STATUS,
	MCA_EVENT_TYPE_SUBPMIC_INFO,
	MCA_EVENT_TYPE_END,
};

enum mca_event_code {
	MCA_EVENT_USB_DISCONNECT = 0x00,
	MCA_EVENT_USB_CONNECT = 0x01,
	MCA_EVENT_WIRELESS_DISCONNECT = 0x02,
	MCA_EVENT_WIRELESS_CONNECT = 0x03,
	MCA_EVENT_WIRELESS_REVCHG = 0x04,
	MCA_EVENT_CHARGE_TYPE_CHANGE = 0x05,
	MCA_EVENT_CHARGE_CAP_CHANGE = 0x06,
	MCA_EVENT_CHARGE_VERIFY_PROCESS_END = 0x07,
	MCA_EVENT_WIRELESS_INT_CHANGE = 0x08,
	MCA_EVENT_WIRELESS_SW_SET_QC_ICHG = 0x09,
	MCA_EVENT_WIRELESS_SW_SET_THERMAL_ICHG = 0x0a,
	MCA_EVENT_WIRELESS_WLS_DEBUG = 0x0b,
	MCA_EVENT_WIRELESS_EPP_MODE = 0x0c,
	MCA_EVENT_WIRELESS_MAGNETIC_QUIT_QC = 0x0d,
	MCA_EVENT_WIRELESS_AUDIO_PHONE_STS = 0x0e,
	MCA_EVENT_WIRELESS_THERMAL_PHONE_FLAG = 0x0f,
	MCA_EVENT_WIRELESS_USB_REVCHG = 0x10,
	MCA_EVENT_BATTERY_STS_CHANGE = 0x11,
	MCA_EVENT_BATTERY_FAKE_POWER = 0x12,
	MCA_EVENT_BATTERY_HEALTH_CHANGE = 0x13,
	MCA_EVENT_PARALLEL_ITERM = 0x14,
	MCA_EVENT_CP_VUSB_INSERT = 0x15,
	MCA_EVENT_CP_VUSB_OUT = 0x16,
	MCA_EVENT_CP_VUSB_OVP = 0x17,
	MCA_EVENT_CP_VBAT_OVP = 0x18,
	MCA_EVENT_CP_VBUS_OVP = 0x19,
	MCA_EVENT_CP_VWPC_OVP = 0x1a,
	MCA_EVENT_CP_PMID2OUT_OVP = 0x1b,
	MCA_EVENT_CP_PMID2OUT_UVP = 0x1c,
	MCA_EVENT_CP_IBAT_OCP = 0x1d,
	MCA_EVENT_CP_IBUS_OCP = 0x1e,
	MCA_EVENT_CP_IBUS_UCP = 0x1f,
	MCA_EVENT_CP_CBOOT_FAIL = 0x20,
	MCA_EVENT_CP_VOUT_UVLO = 0x21,
	MCA_EVENT_CP_POR_FLAG = 0x22,
	MCA_EVENT_CP_IIC_ERROR = 0x23,
	MCA_EVENT_CP_TSHUT_FLAG = 0x24,
	MCA_EVENT_CP_MODE_CHANGE = 0x25,
	MCA_EVENT_CONN_ANTIBURN_CHANGE = 0x26,
	MCA_EVENT_BATT_BTB_CHANGE = 0x27,
	MCA_EVENT_BATT_AUTH_PASS = 0x28,
	MCA_EVENT_LPD_STATUS_CHANGE = 0x29,
	MCA_EVENT_PMIC_INIT_DONE = 0x2a,
	MCA_EVENT_CC_SHORT_VBUS = 0x2b,
	MCA_EVENT_VBAT_OVP_CHANGE = 0x2c,
	MCA_EVENT_IBAT_OCP_CHANGE = 0x2d,
	MCA_EVENT_CP_REVERT_CHANGE = 0x2e,
	MCA_EVENT_USB_STS_CHANGE = 0x2f,
	MCA_EVENT_CHARGE_ABNORMAL = 0x30,
	MCA_EVENT_CHARGE_RESTORE = 0x31,
	MCA_EVENT_SOC_LIMIT = 0x32,
	MCA_EVENT_BATTERY_DTPT = 0x33,
	MCA_EVENT_CSD_SEND_PULSE = 0x34,
	MCA_EVENT_PPS_PTF = 0x35,
	MCA_EVENT_IS_EU_MODEL = 0x36,
	MCA_EVENT_PLATE_SHOCK = 0x37,
	MCA_EVENT_START_QUICK_REVCHG = 0x38,
	MCA_EVENT_REVCHG_BCL = 0x39,
	MCA_EVENT_HANDLE_ALLOW_CHARGE = 0x3a,
	MCA_EVENT_MASTER_BATT_CLOSE = 0x3b,
	MCA_EVENT_THERMAL_BOARD_TEMP_CHANGE = 0x3c,
	MCA_EVENT_CHARGE_RECHARGE_CHECK = 0x3d,
	MCA_EVENT_PANEL_SCREEN_STATE_CHANGE = 0x3e,
	MCA_EVENT_PANEL_HBM_STATE_CHANGE = 0x3f,
	MCA_EVENT_CC_TOGGLE_CHANGE = 0x40,
	MCA_EVENT_BQ_FG_ERROR = 0x41,
	MCA_EVENT_CHARGE_ACTION = 0x42,
	MCA_EVENT_SINK_PWR_SUSPEND_CHANGE = 0x43,
	MCA_EVENT_RESERVED_44 = 0x44,
	MCA_EVENT_USB_SUSPEND = 0x45,
	MCA_EVENT_WIRELESS_MAGNETIC_CASE_INT = 0x46,
	MCA_EVENT_FG_OTA_PROCESS = 0x47,
	MCA_EVENT_FCC_TOO_LOW = 0x48,
	MCA_EVENT_RESERVED_49 = 0x49,
	MCA_EVENT_DEBUG_CTRL_DOUBLE85 = 0x4a,
	MCA_EVENT_DEBUG_CTRL_REMOVE_TEMP_LIMIT = 0x4b,
	MCA_EVENT_DEBUG_CTRL_MEMORY_TEST = 0x4c,
	MCA_EVENT_DEBUG_CTRL_SOC_LIMIT = 0x4d,
	MCA_EVENT_RESERVED_4E = 0x4e,
	MCA_EVENT_PEN_HALL_CHANGE = 0x4f,
	MCA_EVENT_PEN_PPE_HALL_CHANGE = 0x50,
	MCA_EVENT_SBU_LPD_CHANGE = 0x51,
	MCA_EVENT_MAX = 0x52,
};

enum MCA_BATT_CHGR_STATUS_TYPE {
	MCA_BATT_CHGR_STATUS_INHIBIT,
	MCA_BATT_CHGR_STATUS_TRICKLE,
	MCA_BATT_CHGR_STATUS_PRECHARGE,
	MCA_BATT_CHGR_STATUS_FULLON,
	MCA_BATT_CHGR_STATUS_TAPER,
	MCA_BATT_CHGR_STATUS_TERMINATION,
	MCA_BATT_CHGR_STATUS_PAUSE,
	MCA_BATT_CHGR_STATUS_CHARGING_DISABLED,
	MCA_BATT_CHGR_STATUS_FAST_LINEAR,
};

struct mca_event_notify_data {
	const char *event;
	int event_len;
};

int mca_event_block_notify_register(unsigned int type,
				    struct notifier_block *nb);
int mca_event_block_notify_unregister(unsigned int type,
				      struct notifier_block *nb);
void mca_event_block_notify(unsigned int type, unsigned long event, void *data);
void mca_event_report_uevent(const struct mca_event_notify_data *n_data);
void mca_event_report_multiple_uevent(const struct mca_event_notify_data *n_data,
				      unsigned int num);

#endif /* _MCA_COMMON_MCA_EVENT_H_ */
