# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_strategy_fg_class.o mca_strategy_fg_comp.o
mca_strategy_fg_comp-objs := mca_strategy_fg.o mca_soc_smooth.o mca_battery_shutdown.o
