subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mca/include
subdir-ccflags-y += -I$(srctree)/drivers/misc/hwid

obj-$(CONFIG_XM_POWER_SUPPLY) += mca_common/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_shared_memory/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_platform/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_protocol/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_strategy/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_business/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_hardware_monitor/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_smart_charge/
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_hardware_ic/
obj-$(CONFIG_MCA_QCOM_SUBPMIC) += mca_qcom_subpmic_proxy/
obj-$(CONFIG_MCA_QCOM_SYSFS) += mca_qcom_sysfs/
obj-$(CONFIG_MCA_UT_TEST) += mca_ut_test/
