ccflags-y += -I$(srctree)/drivers/misc/hwid

obj-$(CONFIG_XM_POWER_SUPPLY) += mca_vbat_ovp_monitor.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_ibat_ocp_monitor.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_lpd_detect.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_path_control.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_bmd.o
